-- AlterTable
ALTER TABLE "Invoice"
ADD COLUMN "splitCash" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "splitUpi" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "splitCard" DOUBLE PRECISION NOT NULL DEFAULT 0;
